// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1G7G0-D_M2N6jxfh9DtTyCJfnyS-iYo4',
    appId: '1:220045605228:web:dcf3645624b50006249b49',
    messagingSenderId: '220045605228',
    projectId: 'ecommerce-c0cd4',
    authDomain: 'ecommerce-c0cd4.firebaseapp.com',
    storageBucket: 'ecommerce-c0cd4.firebasestorage.app',
    measurementId: 'G-F7ZX9QJDPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6tc3c-taXVUfm2JcaZous5atImPgAFMw',
    appId: '1:220045605228:android:a27e9e3eb4e249fe249b49',
    messagingSenderId: '220045605228',
    projectId: 'ecommerce-c0cd4',
    storageBucket: 'ecommerce-c0cd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ZipAZoW7BDQRezbsZQFnIYf5OxHKRrc',
    appId: '1:220045605228:ios:a3bc3bfc0d22c625249b49',
    messagingSenderId: '220045605228',
    projectId: 'ecommerce-c0cd4',
    storageBucket: 'ecommerce-c0cd4.firebasestorage.app',
    iosBundleId: 'com.example.tpcont',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ZipAZoW7BDQRezbsZQFnIYf5OxHKRrc',
    appId: '1:220045605228:ios:a3bc3bfc0d22c625249b49',
    messagingSenderId: '220045605228',
    projectId: 'ecommerce-c0cd4',
    storageBucket: 'ecommerce-c0cd4.firebasestorage.app',
    iosBundleId: 'com.example.tpcont',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1G7G0-D_M2N6jxfh9DtTyCJfnyS-iYo4',
    appId: '1:220045605228:web:23c0231b59c63de9249b49',
    messagingSenderId: '220045605228',
    projectId: 'ecommerce-c0cd4',
    authDomain: 'ecommerce-c0cd4.firebaseapp.com',
    storageBucket: 'ecommerce-c0cd4.firebasestorage.app',
    measurementId: 'G-R133KPPPZK',
  );
}
